AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions IAM Role - Template for deploying repository-specific GitHub Actions roles that assume the shared OIDC provider'

# Stack Name: github-role-for-simple-saml-idp

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Repository Configuration
        Parameters:
          - Organization
          - ProjectName
          - Environment
      - Label:
          default: Infrastructure References
        Parameters:
          - OIDCProviderStackName
          - TerraformAccessPolicyAccountID
    ParameterLabels:
      Organization:
        default: GitHub Organization
      ProjectName:
        default: Repository Name
      Environment:
        default: Environment
      OIDCProviderStackName:
        default: OIDC Provider Stack Name
      TerraformAccessPolicyAccountID:
        default: Terraform Access Policy Account ID

Parameters:
  Organization:
    Type: String
    Description: GitHub organization name
    Default: faccomichele
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  ProjectName:
    Type: String
    Description: Name of the GitHub repository (change this when copying to another repo)
    Default: simple-saml-idp
    MinLength: 1
    MaxLength: 100
    AllowedPattern: ^[a-zA-Z0-9._-]+$
    ConstraintDescription: Must be a valid GitHub repository name
  
  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
  
  OIDCProviderStackName:
    Type: String
    Description: Name of the stack that deployed the GitHub OIDC provider
    Default: github-identity-provider
  
  TerraformAccessPolicyAccountID:
    Type: String
    Description: The account ID for Terraform access managed policy (from terraform-core-aws stack)

Resources:
  # IAM role for GitHub Actions (repository-specific)
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      # Role name will be auto-generated by CloudFormation with stack name prefix
      # This ensures uniqueness and follows AWS naming best practices
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 
                - 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
                - {}
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${Organization}/${ProjectName}:*'
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      ManagedPolicyArns:
        # REQUIRED: SSM parameter read policy to retrieve Terraform backend configuration
        - !Sub 'arn:aws:iam::${TerraformAccessPolicyAccountID}:policy/terraform-core-aws-tf-access-dev'
      # Inline policy with required Terraform permissions
      Policies:
        - PolicyName: TerraformDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Lambda permissions
              - Sid: LambdaManagement
                Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:ListVersionsByFunction
                  - lambda:PublishLayerVersion
                  - lambda:DeleteLayerVersion
                  - lambda:GetLayerVersion
                  - lambda:TagResource
                  - lambda:UntagResource
                  - lambda:ListTags
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:GetPolicy
                Resource:
                  - !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:simple-saml-idp-*-${Environment}'
                  - !Sub 'arn:aws:lambda:*:${AWS::AccountId}:layer:simple-saml-idp-*-${Environment}'
                  - !Sub 'arn:aws:lambda:*:${AWS::AccountId}:layer:simple-saml-idp-*-${Environment}:*'
              
              # API Gateway permissions
              - Sid: APIGatewayManagement
                Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:PATCH
                  - apigateway:DELETE
                  - apigateway:TagResource
                  - apigateway:UntagResource
                Resource:
                  - !Sub 'arn:aws:apigateway:*::/apis'
                  - !Sub 'arn:aws:apigateway:*::/apis/*'
                  - !Sub 'arn:aws:apigateway:*::/tags/*'
              
              # DynamoDB permissions
              - Sid: DynamoDBManagement
                Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - dynamodb:TagResource
                  - dynamodb:UntagResource
                  - dynamodb:UpdateTable
                  - dynamodb:UpdateContinuousBackups
                  - dynamodb:UpdateTimeToLive
                Resource:
                  - !Sub 'arn:aws:dynamodb:*:${AWS::AccountId}:table/simple-saml-idp-*-${Environment}'
              
              # SSM Parameter Store permissions
              - Sid: SSMParameterManagement
                Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:DescribeParameters
                  - ssm:AddTagsToResource
                  - ssm:RemoveTagsFromResource
                  - ssm:ListTagsForResource
                Resource:
                  - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/simple-saml-idp/${Environment}/*'
              
              # S3 permissions
              - Sid: S3BucketManagement
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicy
                  - s3:GetBucketVersioning
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketAcl
                  - s3:GetBucketCORS
                  - s3:GetBucketLogging
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketTagging
                  - s3:GetBucketWebsite
                  - s3:GetLifecycleConfiguration
                  - s3:GetReplicationConfiguration
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketObjectLockConfiguration
                  - s3:PutBucketPolicy
                  - s3:PutBucketVersioning
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketAcl
                  - s3:PutBucketTagging
                  - s3:DeleteBucketPolicy
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucketVersions
                  - s3:ListBucketMultipartUploads
                  - s3:AbortMultipartUpload
                  - s3:PutObjectAcl
                  - s3:PutObjectTagging
                  - s3:GetObjectTagging
                  - s3:GetObjectAcl
                  - s3:PutLifecycleConfiguration
                Resource:
                  - !Sub 'arn:aws:s3:::simple-saml-idp-login-${Environment}-*'
                  - !Sub 'arn:aws:s3:::simple-saml-idp-login-${Environment}-*/*'

              # CloudFront permissions (conditional - only needed if enable_cloudfront = true)
              - Sid: CloudFrontManagement
                Effect: Allow
                Action:
                  - cloudfront:CreateDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:TagResource
                  - cloudfront:ListTagsForResource
                  - cloudfront:CreateCloudFrontOriginAccessIdentity
                  - cloudfront:GetCloudFrontOriginAccessIdentity
                  - cloudfront:DeleteCloudFrontOriginAccessIdentity
                Resource: '*'

              # IAM permissions for Lambda execution role
              - Sid: IAMRoleManagement
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:ListRoleTags
                  - iam:ListInstanceProfilesForRole
                  - iam:PassRole
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/simple-saml-idp-lambda-${Environment}'
              
              # IAM permissions for managed policies (read-only)
              - Sid: IAMPolicyReadAccess
                Effect: Allow
                Action:
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListPolicyVersions
                Resource:
                  - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
              
              # CloudWatch Logs permissions (for Lambda and API Gateway)
              - Sid: CloudWatchLogsManagement
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:ListTagsLogGroup
                  - logs:TagLogGroup
                  - logs:UntagLogGroup
                  - logs:PutRetentionPolicy
                  - logs:DeleteRetentionPolicy
                Resource:
                  - !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/lambda/simple-saml-idp-*-${Environment}'
                  - !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/lambda/simple-saml-idp-*-${Environment}:*'
                  - !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/apigateway/simple-saml-idp-${Environment}'
                  - !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/apigateway/simple-saml-idp-${Environment}:*'
              
              # Terraform state and resource discovery
              # Wildcard resource access is required for list/discovery operations that Terraform
              # uses to refresh state and detect drift. apigateway:GET is intentionally duplicated
              # here for discovery, while APIGatewayManagement has scoped resources for CRUD operations.
              - Sid: ResourceDiscovery
                Effect: Allow
                Action:
                  - apigateway:GET
                  - lambda:ListFunctions
                  - lambda:GetFunctionCodeSigningConfig
                  - dynamodb:ListTables
                  - ssm:DescribeParameters
                  - s3:ListAllMyBuckets
                  - iam:ListRoles
                  - cloudfront:ListDistributions
                  - cloudfront:ListCloudFrontOriginAccessIdentities
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: cloudformation
        - Key: RepositoryFile
          Value: github-iam-role.yaml
        - Key: Description
          Value: !Sub 'IAM role for GitHub Actions in ${Organization}/${ProjectName}'
        - Key: Region
          Value: !Ref 'AWS::Region'

Outputs:  
  GitHubActionsRoleArn:
    Description: ARN of the IAM role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArn'

